name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0
      - name: test
        run: |
          for dir in {01..10}; do
            terraform -chdir=$dir fmt -check
            terraform -chdir=$dir test
          done
